import type { Job } from "./jobModels";
import type { Employee } from "./employeeModels";

/**
 * Represents a timesheet entry for an employee's work session.
 * Only TimeIn, JobID, EmployeeID, and SiteManagerID are required when creating a new timesheet.
 * Other fields are handled by the backend.
 */
export interface Timesheet {
    /** Unique identifier for the timesheet. Generated by the backend. */
    id?: string;
    /** Date and time of check-in. Required when creating. */
    timeIn: string;
    /** Date and time of check-out. Set when checking out. */
    timeOut?: string;
    /** Foreign key to the Job. Required when creating. */
    jobID: string;
    /** Navigation property for the related Job. */
    job?: Job;
    /** Foreign key to the Employee. Required when creating. */
    employeeID: string;
    /** Navigation property for the related Employee. */
    employee?: Employee;
    /** Foreign key to the SiteManager. Required when creating. */
    siteManagerID: string;
    /** Navigation property for the related SiteManager. */
    user?: Employee;
    /** Indicates if the timesheet is soft-deleted. Handled by backend. */
    deleted?: boolean;
    /** Date/time the entity was created. Handled by backend. */
    timeStamp?: string;
}
