import type { Job } from "./jobModels";
import type { Employee } from "./employeeModels";

/**
 * Represents a timesheet entry for an employee's work session.
 * Only TimeIn, JobID, EmployeeID, and SiteManagerID are required when creating a new timesheet.
 * Other fields are handled by the backend.
 */
export interface Timesheet {
    /** Unique identifier for the timesheet. Generated by the backend. */
    Id?: string;
    /** Date and time of check-in. Required when creating. */
    TimeIn: string;
    /** Date and time of check-out. Set when checking out. */
    TimeOut?: string;
    /** Foreign key to the Job. Required when creating. */
    JobID: string;
    /** Navigation property for the related Job. */
    Job?: Job;
    /** Foreign key to the Employee. Required when creating. */
    EmployeeID: string;
    /** Navigation property for the related Employee. */
    Employee?: Employee;
    /** Foreign key to the SiteManager. Required when creating. */
    SiteManagerID: string;
    /** Navigation property for the related SiteManager. */
    User?: Employee;
    /** Indicates if the timesheet is soft-deleted. Handled by backend. */
    Deleted?: boolean;
    /** Date/time the entity was created. Handled by backend. */
    TimeStamp?: string;
}
